name: Android CI

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  createArtifacts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Read Go version from project
      run: echo "GO_VERSION=$(grep -E "^de\.felixnuesse\.extract\.goVersion=" gradle.properties | cut -d'=' -f2)"
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Set up Go from gradle.properties
      uses: actions/setup-go@v4
      with:
        go-version: '${{env.GO_VERSION}}'
      id: go
    - name: Setup Android SDK/NDK
      uses: android-actions/setup-android@v3
    - name: Install NDK from gradle.properties
      run: |
        NDK_VERSION="$(grep -E "^de\.felixnuesse\.extract\.ndkVersion=" gradle.properties | cut -d'=' -f2)"
        sdkmanager "ndk;${NDK_VERSION}"
    - name: Build app
      run: ./gradlew assembleOssRelease
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: nightly-armeabi.apk
        path: ${{ github.workspace }}/app/build/outputs/apk/oss/**/*
